### ISSUE TITLE
error while installing metasploit framework

### ISSUE THREAD

**Issue by luceifer** [efxtv/Metasploit-in-termux#1]
Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change the sources in
your Gemfile from 'https' to 'http'. Instructions for compiling with
OpenSSL using RVM are available at https://rvm.io/packages/openssl.
![Screenshot_20220306-001518_Termux](https://user-images.githubusercontent.com/60282815/156901530-05cd2962-d25e-45f6-9f1e-873e9bf8e915.png)

**Comment by RazerXT** [comment]
Same error to me

**Comment by RazerXT** [comment]
Please give some solution

**Comment by Zazbhai** [comment]
Same bro

**Comment by efxtv** [comment]
Please use latest update.

**Comment by efxtv** [comment]
Please close the case if it worked with the latest script. Thank you

**Comment by Zazbhai** [comment]
> Please close the case if it worked with the latest script. Thank you

So Where is New Version

**Comment by luceifer** [comment]
I'll close for now till trying the new version.

**Comment by efxtv** [comment]
check efx tv official latest video.
