### ISSUE TITLE
(Msf::OptionValidateError)

### ISSUE THREAD

**Issue by Katrin5** [efxtv/Metasploit-in-termux#12]
Cómo soluciono ese error 
![Screenshot_20220430-025948.png](https://user-images.githubusercontent.com/104668035/166097302-7a9fc247-0961-479a-9b7d-4ae751cdf409.png)

**Comment by dedshit** [comment]
> Cómo soluciono ese error ![Screenshot_20220430-025948.png](https://user-images.githubusercontent.com/104668035/166097302-7a9fc247-0961-479a-9b7d-4ae751cdf409.png)

leave some between portmap.io and Lhost

**Comment by efxtv** [comment]
Check your script and update metasploit6 in termux with our tool's latest version. For more info join t.me/efxtv
