### ISSUE TITLE
Does this method really work 

### ISSUE THREAD

**Issue by ChillVibesMushroom** [efxtv/Metasploit-in-termux#14]
An error occurred while installing sqlite3
(1.5.0), and Bundler cannot continue.

I followed the instructions except for installing termux-api

Before running the metasploit installation script 

I'm also using grimler.se termux repo

There shouldn't be an issue right I mean you covered all fixes in your script.

**Comment by efxtv** [comment]
We are working to get it fixed. Please allow us some time. For real time updates and alternative please join [t.me/efxtv](url) .

**Comment by efxtv** [comment]
Repository has been fixed. Please try again

**Comment by efxtv** [comment]
Here is the fix, tested and working on multiple videos. [Source ](https://youtu.be/c08713O7prU)
