### ISSUE TITLE
gem pry error

### ISSUE THREAD

**Issue by rendykyh** [efxtv/Metasploit-in-termux#18]
help i try install metasploit with mversion and get this error when i execute msfconsole

![metasploit](https://user-images.githubusercontent.com/38185582/211452627-139bf07b-9093-4c59-9722-2ef92b47350c.jpg)

**Comment by Samarweb** [comment]
Bruh wtf is this

**Comment by efxtv** [comment]
Please visit https://youtu.be/KBNXzUlKOwk Subscribe and follow our github if it work for you.
