### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Darkrevengehack** [efxtv/Metasploit-in-termux#21]
[+] Press ENTER button to fix:[+] Okay got it...
[+] Fixing metasploit...
[+] Fixing....
[+] Almost fixed....
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb: No such file or directory                                              sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb: No such file or directory                                              [+] Cheers! Metasploit6 has been installed...
┌─────────────────────────────────────────────────────────
└(u0_a118@) ~ $ msfconsole   58m  Mon Apr  3 12:46:57 2023
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.         Could not find nokogiri-1.8.0 in any of the sources        Run `bundle install` to install missing gems.
┌───────────────────────────────────────────────────────── └(7:u0_a118@) ~ $         4177ms  Mon Apr  3 12:47:31 2023

**Comment by efxtv** [comment]
https://youtu.be/zxSN9TfWRLc
