### ISSUE TITLE
Nekogiri

### ISSUE THREAD

**Issue by Ghostcodz** [efxtv/Metasploit-in-termux#22]
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Could not find nokogiri-1.8.0 in any of the sources

**Comment by efxtv** [comment]
Join t.me/efxtv

**Comment by efxtv** [comment]
It has been fixed please check latest video [here](https://youtube.com/live/SlmMzToAfL4?feature=share)
