### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ultrahacker678** [efxtv/Metasploit-in-termux#4]
When installing: Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change
the sources in your Gemfile from 'https' to 'http'.
Instructions for compiling with OpenSSL using RVM are
available at https://rvm.io/packages/openssl.
When type msfconsole:
Bundler could not find compatible versions for gem "metasploit-payloads":
  In Gemfile:
    metasploit-framework was resolved to 6.1.34, which depends on
      metasploit-payloads (= 2.0.77)

Could not find gem 'metasploit-payloads (= 2.0.77)', which is required by gem 'metasploit-framework', in any of the sources.
P.s.  I use latest update
![Screenshot_20220316-103729_Termux](https://user-images.githubusercontent.com/55056545/158549762-cda9b510-359a-443f-a192-24f45e693061.jpg)

**Comment by efxtv** [comment]
Watch latest fix t.me/efxtv

**Comment by D3VR4J** [comment]
Same error: how to fix?

**Comment by Mahesh899** [comment]
![Screenshot_2022-03-27-12-28-26-60_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/102238209/160270442-b89ebfeb-f4ed-4f5b-849b-e71986337023.jpg)same problem bro

**Comment by ultrahacker678** [comment]
> When installing: Could not load OpenSSL. You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using RVM are available at https://rvm.io/packages/openssl. When type msfconsole: Bundler could not find compatible versions for gem "metasploit-payloads": In Gemfile: metasploit-framework was resolved to 6.1.34, which depends on metasploit-payloads (= 2.0.77)
> 
> Could not find gem 'metasploit-payloads (= 2.0.77)', which is required by gem 'metasploit-framework', in any of the sources. P.s. I use latest update ![Screenshot_20220316-103729_Termux](https://user-images.githubusercontent.com/55056545/158549762-cda9b510-359a-443f-a192-24f45e693061.jpg)

Last fix working!(How to fix: reset termux data, install metasploit, do all commands)

**Comment by ultrahacker678** [comment]
> When installing: Could not load OpenSSL. You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using RVM are available at https://rvm.io/packages/openssl. When type msfconsole: Bundler could not find compatible versions for gem "metasploit-payloads": In Gemfile: metasploit-framework was resolved to 6.1.34, which depends on metasploit-payloads (= 2.0.77)
> 
> Could not find gem 'metasploit-payloads (= 2.0.77)', which is required by gem 'metasploit-framework', in any of the sources. P.s. I use latest update ![Screenshot_20220316-103729_Termux](https://user-images.githubusercontent.com/55056545/158549762-cda9b510-359a-443f-a192-24f45e693061.jpg)
