### ISSUE TITLE
How to fix pls tell me

### ISSUE THREAD

**Issue by Barath666** [efxtv/Metasploit-in-termux#5]
![Screenshot_2022-03-17-06-44-58-952_com termux](https://user-images.githubusercontent.com/101777305/158718003-c6d9facc-f200-4dc3-ac97-ddb90995deec.jpg)

**Comment by efxtv** [comment]
cd metasploit-framework;
sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb

**Comment by dedshit** [comment]
its my fix dont you give credits

**Comment by efxtv** [comment]
Please share the proof. I'll share your name. Please get in touch on t.me/efxtv

**Comment by efxtv** [comment]
I've done so many changes. I just want to see what and where you have done this prior to me.

**Comment by dedshit** [comment]
> I've done so many changes. I just want to see what and where you have done this prior to me.


lmao

**Comment by efxtv** [comment]
Please get in touch on t.me/efxtve and talk about it. Sorry if I made mistake. I'll do what you say okay.

Regards 
Efxtv
