### ISSUE TITLE
When I use msfvenom I facing problem 

### ISSUE THREAD

**Issue by arav0125** [efxtv/Metasploit-in-termux#8]
![Screenshot_20220322_085551](https://user-images.githubusercontent.com/91102859/159402044-5799e0be-c01f-4ee1-9ed1-c24f293ac365.jpg)

Help me
Please 
Device=vivo1820
Vivo y91i

**Comment by Cool1l** [comment]
Hello even I have samme device paste this in terminal and hit enter ur probpem will be solved

rm -rf /data/data/com.termux/files/usr/bin/msfvenom

cd;cd metasploit-framework;ln -s $HOME/metasploit-framework/msfvenom /data/data/com.termux/files/usr/bin

**Comment by washim73** [comment]
![Screenshot_20220322-183539_Termux](https://user-images.githubusercontent.com/102160242/159488643-24d8421c-62fc-4265-a34d-2a5cbe6b7688.jpg)
I face this problem
😔😔😔

**Comment by subzero914** [comment]
Nn sei resolver esse problema... Mais  isso ocorreu pq vc apagou o msfvenom... Qnd vc usou aquele comando rm -rf /data/...msfvenom...  e talz... Pq o comando rm eh para remover arquivos

**Comment by efxtv** [comment]
update required
