### ISSUE TITLE
Msfvenom

### ISSUE THREAD

**Issue by washim73** [efxtv/Metasploit-in-termux#9]
I can not open msfvenom plz help me
![Screenshot_20220322-183539_Termux](https://user-images.githubusercontent.com/102160242/159488488-8a778838-2e7c-49c0-bdef-2d1aa57ca5c3.jpg)

**Comment by subzero914** [comment]
Não sei resolver esse problema... Mais isso aconteceu pq vc apagou o msvenom... Qnd vc usou esse problema daquele comando r - rf /data/msfvenom... e talz... Pq o comando rm eh para removedor de arquivos

**Comment by Aadhi497** [comment]
bro msfvenom not creating a file type like a apk , exe..

**Comment by Aadhi497** [comment]
during 2 days video this error accoured pls help

**Comment by Aadhi497** [comment]
-![Screenshot_2022-04-16-11-44-53-463_com.termux.jpg](https://user-images.githubusercontent.com/103766147/163664165-8c4c0543-72a8-4539-873d-9f042207caa4.jpg)

**Comment by Aadhi497** [comment]
![Screenshot_2022-04-16-11-44-51-684_com.termux.jpg](https://user-images.githubusercontent.com/103766147/163664191-e52d7968-eb63-4e85-8531-fc223d34a000.jpg)

**Comment by Aadhi497** [comment]
exe and apk 2 also not working bro

**Comment by Benito37** [comment]
Hi guys, I also have a problem with msfvenom, can someone help me solve it please?
![image](https://user-images.githubusercontent.com/103997838/164225233-5031dbf4-e8bf-43d9-8039-aff50ea05cfd.jpeg)
